export const TURKEY_CITIES: Record<string, string[]> = {
  'Adana': ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Karaisalı', 'Karataş', 'Pozantı', 'Aladağ', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Yumurtalık'],
  'Adıyaman': ['Merkez', 'Kahta', 'Besni', 'Gölbaşı', 'Gerger', 'Çelikhan', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Merkez', 'Sandıklı', 'Dinar', 'Bolvadin', 'Emirdağ', 'Çay', 'Sultandağı', 'İhsaniye', 'Şuhut', 'Sinanpaşa', 'İscehisar', 'Bayat', 'Başmakçı', 'Dazkırı', 'Evciler', 'Hocalar', 'Kızılören', 'Çobanlar'],
  'Ağrı': ['Merkez', 'Doğubayazıt', 'Patnos', 'Eleşkirt', 'Diyadin', 'Tutak', 'Hamur', 'Taşlıçay'],
  'Aksaray': ['Merkez', 'Ortaköy', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Ağaçören', 'Sarıyahşi'],
  'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Gümüşhacıköy', 'Göynücek', 'Hamamözü', 'Taşova'],
  'Ankara': ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan', 'Altındağ', 'Pursaklar', 'Gölbaşı', 'Polatlı', 'Çubuk', 'Beypazarı', 'Kahramankazan', 'Haymana', 'Şereflikoçhisar', 'Kızılcahamam', 'Akyurt', 'Elmadağ', 'Bala', 'Ayaş', 'Nallıhan', 'Güdül', 'Evren', 'Kalecik', 'Çamlıdere'],
  'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Aksu', 'Döşemealtı', 'Alanya', 'Manavgat', 'Serik', 'Kumluca', 'Kaş', 'Kemer', 'Finike', 'Gazipaşa', 'Demre', 'Elmalı', 'Korkuteli', 'Akseki', 'Gündoğmuş', 'İbradı'],
  'Artvin': ['Merkez', 'Arhavi', 'Hopa', 'Borçka', 'Şavşat', 'Yusufeli', 'Ardanuç', 'Murgul'],
  'Aydın': ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'İncirliova', 'Germencik', 'Çine', 'Sultanhisar', 'Buharkent', 'Bozdoğan', 'Karacasu', 'Koçarlı', 'Kuyucak', 'Köşk', 'Yenipazar', 'Karpuzlu'],
  'Balıkesir': ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Gönen', 'Burhaniye', 'Ayvalık', 'Bigadiç', 'Susurluk', 'Erdek', 'Havran', 'Dursunbey', 'İvrindi', 'Sındırgı', 'Manyas', 'Savaştepe', 'Kepsut', 'Balya', 'Marmara'],
  'Bartın': ['Merkez', 'Ulus', 'Kurucaşile', 'Amasra'],
  'Batman': ['Merkez', 'Kozluk', 'Sason', 'Beşiri', 'Gercüş', 'Hasankeyf'],
  'Bayburt': ['Merkez', 'Aydıntepe', 'Demirözü'],
  'Bilecik': ['Merkez', 'Bozüyük', 'Osmaneli', 'Söğüt', 'Gölpazarı', 'Pazaryeri', 'İnhisar', 'Yenipazar'],
  'Bingöl': ['Merkez', 'Genç', 'Solhan', 'Karlıova', 'Adaklı', 'Kiğı', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak', 'Hizan', 'Mutki', 'Adilcevaz'],
  'Bolu': ['Merkez', 'Gerede', 'Mudurnu', 'Göynük', 'Mengen', 'Seben', 'Yeniçağa', 'Dörtdivan', 'Kıbrıscık'],
  'Burdur': ['Merkez', 'Bucak', 'Gölhisar', 'Yeşilova', 'Tefenni', 'Ağlasun', 'Çavdır', 'Altınyayla', 'Çeltikçi', 'Karamanlı', 'Kemer'],
  'Bursa': ['Osmangazi', 'Nilüfer', 'Yıldırım', 'İnegöl', 'Gemlik', 'Mudanya', 'Gürsu', 'Kestel', 'Mustafakemalpaşa', 'Karacabey', 'Orhangazi', 'İznik', 'Yenişehir', 'Orhaneli', 'Büyükorhan', 'Harmancık', 'Keles'],
  'Çanakkale': ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Ezine', 'Ayvacık', 'Bayramiç', 'Lapseki', 'Yenice', 'Gökçeada', 'Bozcaada'],
  'Çankırı': ['Merkez', 'Çerkeş', 'Ilgaz', 'Kurşunlu', 'Şabanözü', 'Yapraklı', 'Atkaracalar', 'Bayramören', 'Eldivan', 'Kızılırmak', 'Korgun', 'Orta'],
  'Çorum': ['Merkez', 'Sungurlu', 'Osmancık', 'Alaca', 'İskilip', 'Kargı', 'Bayat', 'Mecitözü', 'Boğazkale', 'Dodurga', 'Laçin', 'Oğuzlar', 'Ortaköy', 'Uğurludağ'],
  'Denizli': ['Merkezefendi', 'Pamukkale', 'Çivril', 'Acıpayam', 'Tavas', 'Buldan', 'Çal', 'Honaz', 'Sarayköy', 'Kale', 'Serinhisar', 'Güney', 'Bekilli', 'Bozkurt', 'Çardak', 'Çameli', 'Babadağ', 'Baklan', 'Beyağaç'],
  'Diyarbakır': ['Bağlar', 'Kayapınar', 'Yenişehir', 'Sur', 'Ergani', 'Bismil', 'Silvan', 'Çermik', 'Çınar', 'Dicle', 'Eğil', 'Hani', 'Hazro', 'Kocaköy', 'Kulp', 'Lice', 'Çüngüş'],
  'Düzce': ['Merkez', 'Akçakoca', 'Kaynaşlı', 'Gölyaka', 'Cumayeri', 'Çilimli', 'Gümüşova', 'Yığılca'],
  'Edirne': ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala', 'Havsa', 'Enez', 'Süloğlu', 'Lalapaşa', 'Meriç'],
  'Elazığ': ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu', 'Maden', 'Baskil', 'Sivrice', 'Arıcak', 'Keban', 'Ağın', 'Alacakaya'],
  'Erzincan': ['Merkez', 'Üzümlü', 'Tercan', 'Refahiye', 'Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Otlukbeli'],
  'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan', 'Pasinler', 'Hınıs', 'Karayazı', 'Aşkale', 'İspir', 'Tortum', 'Narman', 'Tekman', 'Şenkaya', 'Köprüköy', 'Çat', 'Karaçoban', 'Olur', 'Pazaryolu', 'Uzundere'],
  'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Çifteler', 'Sivrihisar', 'Mahmudiye', 'Alpu', 'Beylikova', 'İnönü', 'Mihalgazi', 'Mihalıççık', 'Günyüzü', 'Han', 'Sarıcakaya', 'Seyitgazi'],
  'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Araban', 'Yavuzeli', 'Karkamış'],
  'Giresun': ['Merkez', 'Bulancak', 'Görele', 'Espiye', 'Tirebolu', 'Keşap', 'Eynesil', 'Piraziz', 'Dereli', 'Yağlıdere', 'Şebinkarahisar', 'Alucra', 'Güce', 'Çanakçı', 'Çamoluk', 'Doğankent'],
  'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Köse', 'Kürtün'],
  'Hakkari': ['Merkez', 'Yüksekova', 'Şemdinli', 'Çukurca', 'Derecik'],
  'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Arsuz', 'Payas', 'Dörtyol', 'Kırıkhan', 'Reyhanlı', 'Samandağ', 'Altınözü', 'Belen', 'Erzin', 'Hassa', 'Kumlu', 'Yayladağı'],
  'Iğdır': ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'],
  'Isparta': ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Gelendost', 'Senirkent', 'Keçiborlu', 'Sütçüler', 'Uluborlu', 'Gönen', 'Atabey', 'Aksu', 'Yenişarbademli'],
  'İstanbul': ['Kadıköy', 'Üsküdar', 'Beşiktaş', 'Şişli', 'Fatih', 'Beyoğlu', 'Bakırköy', 'Ataşehir', 'Maltepe', 'Kartal', 'Pendik', 'Tuzla', 'Ümraniye', 'Sarıyer', 'Beykoz', 'Çekmeköy', 'Sancaktepe', 'Sultanbeyli', 'Küçükçekmece', 'Bağcılar', 'Bahçelievler', 'Güngören', 'Esenler', 'Bayrampaşa', 'Gaziosmanpaşa', 'Sultangazi', 'Eyüpsultan', 'Kağıthane', 'Zeytinburnu', 'Avcılar', 'Esenyurt', 'Başakşehir', 'Büyükçekmece', 'Arnavutköy', 'Çatalca', 'Silivri', 'Şile', 'Adalar', 'Beylikdüzü'],
  'İzmir': ['Konak', 'Bornova', 'Karşıyaka', 'Buca', 'Bayraklı', 'Çiğli', 'Gaziemir', 'Karabağlar', 'Narlıdere', 'Balçova', 'Torbalı', 'Menemen', 'Ödemiş', 'Bergama', 'Tire', 'Aliağa', 'Kemalpaşa', 'Urla', 'Çeşme', 'Dikili', 'Foça', 'Menderes', 'Seferihisar', 'Selçuk', 'Bayındır', 'Kiraz', 'Beydağ', 'Karaburun', 'Güzelbahçe'],
  'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Göksun', 'Türkoğlu', 'Pazarcık', 'Andırın', 'Çağlayancerit', 'Ekinözü', 'Nurhak'],
  'Karabük': ['Merkez', 'Safranbolu', 'Yenice', 'Eflani', 'Eskipazar', 'Ovacık'],
  'Karaman': ['Merkez', 'Ermenek', 'Sarıveliler', 'Başyayla', 'Kazımkarabekir', 'Ayrancı'],
  'Kars': ['Merkez', 'Sarıkamış', 'Kağızman', 'Selim', 'Arpaçay', 'Digor', 'Susuz', 'Akyaka'],
  'Kastamonu': ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu', 'Araç', 'Cide', 'Daday', 'Devrekani', 'Abana', 'Küre', 'Çatalzeytin', 'Azdavay', 'Bozkurt', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'Pınarbaşı', 'Seydiler', 'Şenpazar'],
  'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'Hacılar', 'İncesu', 'Develi', 'Bünyan', 'Yahyalı', 'Tomarza', 'Pınarbaşı', 'Sarıoğlan', 'Felahiye', 'Özvatan', 'Akkışla', 'Sarız', 'Yeşilhisar'],
  'Kırıkkale': ['Merkez', 'Yahşihan', 'Keskin', 'Delice', 'Sulakyurt', 'Bahşili', 'Balışeyh', 'Çelebi', 'Karakeçili'],
  'Kırklareli': ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Pınarhisar', 'Demirköy', 'Kofçaz', 'Pehlivanköy'],
  'Kırşehir': ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı', 'Akpınar', 'Akçakent', 'Boztepe'],
  'Kilis': ['Merkez', 'Musabeyli', 'Elbeyli', 'Polateli'],
  'Kocaeli': ['İzmit', 'Gebze', 'Darıca', 'Çayırova', 'Dilovası', 'Körfez', 'Gölcük', 'Kartepe', 'Başiskele', 'Derince', 'Kandıra', 'Karamürsel'],
  'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir', 'Beyşehir', 'Seydişehir', 'Çumra', 'Cihanbeyli', 'Kulu', 'Karapınar', 'Ilgın', 'Kadınhanı', 'Sarayönü', 'Bozkır', 'Hadim', 'Doğanhisar', 'Hüyük', 'Taşkent', 'Altınekin', 'Derbent', 'Derebucak', 'Emirgazi', 'Güneysınır', 'Halkapınar', 'Tuzlukçu', 'Ahırlı', 'Çeltik', 'Yalıhüyük', 'Yunak'],
  'Kütahya': ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Domaniç', 'Altıntaş', 'Aslanapa', 'Dumlupınar', 'Hisarcık', 'Çavdarhisar', 'Pazarlar', 'Şaphane'],
  'Malatya': ['Battalgazi', 'Yeşilyurt', 'Doğanşehir', 'Akçadağ', 'Darende', 'Hekimhan', 'Arguvan', 'Arapgir', 'Pütürge', 'Yazıhan', 'Kuluncak', 'Kale', 'Doğanyol'],
  'Manisa': ['Yunusemre', 'Şehzadeler', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma', 'Alaşehir', 'Saruhanlı', 'Kırkağaç', 'Demirci', 'Gördes', 'Sarıgöl', 'Selendi', 'Ahmetli', 'Gölmarmara', 'Köprübaşı'],
  'Mardin': ['Artuklu', 'Kızıltepe', 'Nusaybin', 'Midyat', 'Derik', 'Mazıdağı', 'Ömerli', 'Dargeçit', 'Savur', 'Yeşilli'],
  'Mersin': ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus', 'Silifke', 'Erdemli', 'Anamur', 'Mut', 'Gülnar', 'Aydıncık', 'Bozyazı', 'Çamlıyayla'],
  'Muğla': ['Menteşe', 'Bodrum', 'Fethiye', 'Milas', 'Marmaris', 'Ortaca', 'Dalaman', 'Datça', 'Yatağan', 'Kavaklıdere', 'Köyceğiz', 'Ula', 'Seydikemer'],
  'Muş': ['Merkez', 'Bulanık', 'Malazgirt', 'Varto', 'Hasköy', 'Korkut'],
  'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos', 'Gülşehir', 'Derinkuyu', 'Kozaklı', 'Acıgöl', 'Hacıbektaş'],
  'Niğde': ['Merkez', 'Bor', 'Çamardı', 'Ulukışla', 'Altunhisar', 'Çiftlik'],
  'Ordu': ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe', 'Kumru', 'Korgan', 'Gölköy', 'Ulubey', 'Gülyalı', 'Kabataş', 'Aybastı', 'Kabadüz', 'Mesudiye', 'Gürgentepe', 'Çamaş', 'Çatalpınar', 'İkizce', 'Akkuş', 'Çaybaşı'],
  'Osmaniye': ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Toprakkale', 'Hasanbeyli', 'Sumbas'],
  'Rize': ['Merkez', 'Çamlıhemşin', 'Ardeşen', 'Pazar', 'Fındıklı', 'Çayeli', 'İkizdere', 'Derepazarı', 'Hemşin', 'İyidere', 'Güneysu', 'Kalkandere'],
  'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Arifiye', 'Hendek', 'Akyazı', 'Geyve', 'Sapanca', 'Kaynarca', 'Ferizli', 'Karasu', 'Söğütlü', 'Pamukova', 'Taraklı', 'Karapürçek', 'Kocaali'],
  'Samsun': ['İlkadım', 'Atakum', 'Canik', 'Tekkeköy', 'Bafra', 'Çarşamba', 'Terme', 'Vezirköprü', 'Havza', 'Ladik', 'Kavak', 'Alaçam', 'Ayvacık', 'Salıpazarı', 'Asarcık', 'Yakakent', '19 Mayıs'],
  'Şanlıurfa': ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Siverek', 'Viranşehir', 'Suruç', 'Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Hilvan', 'Halfeti', 'Harran'],
  'Siirt': ['Merkez', 'Kurtalan', 'Pervari', 'Eruh', 'Baykan', 'Şirvan', 'Tillo'],
  'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancık', 'Türkeli', 'Durağan', 'Erfelek', 'Dikmen', 'Saraydüzü'],
  'Sivas': ['Merkez', 'Şarkışla', 'Suşehri', 'Gemerek', 'Zara', 'Kangal', 'Divriği', 'Yıldızeli', 'Hafik', 'Gürün', 'Koyulhisar', 'İmranlı', 'Altınyayla', 'Doğanşar', 'Gölova', 'Akıncılar', 'Ulaş'],
  'Şırnak': ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Uludere', 'Beytüşşebap', 'Güçlükonak'],
  'Tekirdağ': ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Ergene', 'Kapaklı', 'Hayrabolu', 'Malkara', 'Muratlı', 'Saray', 'Şarköy', 'Marmaraereğlisi'],
  'Tokat': ['Merkez', 'Erbaa', 'Turhal', 'Niksar', 'Zile', 'Reşadiye', 'Almus', 'Artova', 'Pazar', 'Başçiftlik', 'Sulusaray', 'Yeşilyurt'],
  'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Of', 'Yomra', 'Arsin', 'Beşikdüzü', 'Vakfıkebir', 'Sürmene', 'Çarşıbaşı', 'Maçka', 'Tonya', 'Düzköy', 'Şalpazarı', 'Çaykara', 'Dernekpazarı', 'Hayrat', 'Köprübaşı'],
  'Tunceli': ['Merkez', 'Pertek', 'Çemişgezek', 'Hozat', 'Ovacık', 'Pülümür', 'Mazgirt', 'Nazımiye'],
  'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Sivaslı', 'Ulubey', 'Karahallı'],
  'Van': ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Özalp', 'Çaldıran', 'Başkale', 'Gevaş', 'Gürpınar', 'Muradiye', 'Bahçesaray', 'Çatak', 'Saray'],
  'Yalova': ['Merkez', 'Çınarcık', 'Altınova', 'Çiftlikköy', 'Armutlu', 'Termal'],
  'Yozgat': ['Merkez', 'Sorgun', 'Yerköy', 'Boğazlıyan', 'Akdağmadeni', 'Sarıkaya', 'Çekerek', 'Şefaatli', 'Çandır', 'Kadışehri', 'Aydıncık', 'Çayıralan', 'Saraykent', 'Yenifakılı'],
  'Zonguldak': ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Gökçebey', 'Alaplı', 'Kilimli', 'Kozlu'],
};

export const CITY_NAMES = Object.keys(TURKEY_CITIES).sort((a, b) => a.localeCompare(b, 'tr'));

export function getDistricts(city: string): string[] {
  return TURKEY_CITIES[city] || [];
}
